ALTER SESSION SET CONTAINER=XEPDB1;

CREATE USER docker IDENTIFIED BY Passw0rd
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users
TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION TO docker;
GRANT RESOURCE TO docker;
GRANT UNLIMITED TABLESPACE TO docker;